name: Test PR
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'
      - 'examples'
      - '!examples/monaco-graphql-webpack'
jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: ['14', '16', '17', '18']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --immutable

      - name: Build
        run: yarn build

      - name: Run Unit Tests
        run: yarn test --coverage

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: coverage

  e2e:
    name: Cypress E2E Suite
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --immutable

      - name: Run E2E suite
        run: yarn e2e
